"""Load the hand-written strategy for a transport mode.

Two halves make a prompt, and keeping them apart is the whole point.

**Reference** is what an action is called and what it takes. Generated by
``action_brief`` from nttd's manifest, so it cannot describe an action that does not
exist.

**Strategy** is what a manifest cannot know: what order to do things in, which cargo
pays, how to recover from a refusal, when to wait. Hand-written, in ``strategy/*.md``,
and short.

They were mixed together in a 47,000 character file. The reference half went stale, as a
hand-copied reference always does, and the strategy half was buried inside it where
nobody could find or edit it. Roughly 42,000 of those characters were strategy worth
keeping, which is why deleting the whole file was the wrong trade.

The files carry SKILL.md frontmatter (``name`` and ``description``) so they can be handed
to a skills-aware framework later without rewriting. Nothing here requires one: the
frontmatter is stripped when the body is loaded as a prompt.
"""

from __future__ import annotations

from pathlib import Path

_STRATEGY_DIR = Path(__file__).parent / "strategy"
_FRONTMATTER_FENCE = "---"

# Read first, whatever the mode. It holds the rules that decide most runs: finish one
# route before starting another, ask a finder where things fit, and never read a partial
# build as a success.
COMMON = "common"

MODES = ("rail", "road", "water", "air")


def load(mode: str, with_common: bool = True) -> str:
    """The strategy for one mode, as prompt text.

    Args:
        mode: One of ``MODES``.
        with_common: Prepend the shared strategy. Almost always right: the mode files
            deliberately do not repeat it.

    Raises:
        ValueError: no strategy file for that mode. Raised rather than returning an
            empty string, because an agent silently running with no strategy at all
            looks like a bad model rather than a missing file.
    """
    parts = [_read(COMMON)] if with_common else []
    parts.append(_read(mode))
    return "\n\n".join(parts)


def describe(mode: str) -> str:
    """The one-line description from a strategy file's frontmatter.

    Useful for an orchestrator choosing between specialists: it can see what each mode
    is for without loading the whole file into context.
    """
    for line in _raw(mode).splitlines():
        if line.startswith("description:"):
            return line.removeprefix("description:").strip()
    return ""


def _raw(mode: str) -> str:
    path = _STRATEGY_DIR / f"{mode}.md"
    if not path.exists():
        available = sorted(p.stem for p in _STRATEGY_DIR.glob("*.md"))
        raise ValueError(f"No strategy for {mode!r}. Available: {', '.join(available)}")
    return path.read_text()


def _read(mode: str) -> str:
    """The body, with the frontmatter stripped.

    Split on the fence rather than parsed as YAML: the frontmatter carries two scalar
    fields and taking a YAML dependency to read them would be machinery for nothing.
    """
    text = _raw(mode)
    if not text.startswith(_FRONTMATTER_FENCE):
        return text.strip()
    closing = text.find(f"\n{_FRONTMATTER_FENCE}", len(_FRONTMATTER_FENCE))
    if closing == -1:
        return text.strip()
    return text[closing + len(_FRONTMATTER_FENCE) + 1:].strip()
